version: "3.11"

services:
  app:
    build:
      context: .

    env_file:
      - .env

    command: >
      sh -c "
        uvicorn send_email:app --host 0.0.0.0 --port 8000
      "

    ports:
      - "8000:8000"

    restart: always
